{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "7.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-7.0.8.jar",
          "url": "spring-context-7.0.8.jar",
          "size": 1398484,
          "sha512": "817d2ac74c7226c449791e3579ba5589ad919786f59d7ee405baab77ca03c210348b574bb8e69d9368c1c43d800d047c1213a88f60d4c8e6166dc4ba3b69c69f",
          "sha256": "1eb7d552414ebac00e30ab3e809138d810785f6d2c4271db77cdf0181f308f19",
          "sha1": "6c58b590fd8d71afc36797cf6555e82500f1eb64",
          "md5": "32a33f439e7e19ac643f7db75c74680a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.8"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-7.0.8.jar",
          "url": "spring-context-7.0.8.jar",
          "size": 1398484,
          "sha512": "817d2ac74c7226c449791e3579ba5589ad919786f59d7ee405baab77ca03c210348b574bb8e69d9368c1c43d800d047c1213a88f60d4c8e6166dc4ba3b69c69f",
          "sha256": "1eb7d552414ebac00e30ab3e809138d810785f6d2c4271db77cdf0181f308f19",
          "sha1": "6c58b590fd8d71afc36797cf6555e82500f1eb64",
          "md5": "32a33f439e7e19ac643f7db75c74680a"
        }
      ]
    }
  ]
}
