{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.1.0.jar",
          "url": "spring-boot-starter-4.1.0.jar",
          "size": 4765,
          "sha512": "91dfb20dc93041decbfd54574342f81c6fe82ebcdacce251265b5a04c4c04b22c71c52bbb96ed9d2205b036f83950a9ef2ada67c20bd64b427d238c0651c4668",
          "sha256": "40352b3fc0834d5830f66d40100fc8afa8ac73e24a134c7779bd42b72f2d6506",
          "sha1": "4d1f5fcf982ec75223a3ee44169e268b6dd044f7",
          "md5": "e7f22a3cc55d98c2c8030f069c8963a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.1.0.jar",
          "url": "spring-boot-starter-4.1.0.jar",
          "size": 4765,
          "sha512": "91dfb20dc93041decbfd54574342f81c6fe82ebcdacce251265b5a04c4c04b22c71c52bbb96ed9d2205b036f83950a9ef2ada67c20bd64b427d238c0651c4668",
          "sha256": "40352b3fc0834d5830f66d40100fc8afa8ac73e24a134c7779bd42b72f2d6506",
          "sha1": "4d1f5fcf982ec75223a3ee44169e268b6dd044f7",
          "md5": "e7f22a3cc55d98c2c8030f069c8963a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.1.0-javadoc.jar",
          "url": "spring-boot-starter-4.1.0-javadoc.jar",
          "size": 4765,
          "sha512": "91dfb20dc93041decbfd54574342f81c6fe82ebcdacce251265b5a04c4c04b22c71c52bbb96ed9d2205b036f83950a9ef2ada67c20bd64b427d238c0651c4668",
          "sha256": "40352b3fc0834d5830f66d40100fc8afa8ac73e24a134c7779bd42b72f2d6506",
          "sha1": "4d1f5fcf982ec75223a3ee44169e268b6dd044f7",
          "md5": "e7f22a3cc55d98c2c8030f069c8963a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.1.0-sources.jar",
          "url": "spring-boot-starter-4.1.0-sources.jar",
          "size": 4765,
          "sha512": "91dfb20dc93041decbfd54574342f81c6fe82ebcdacce251265b5a04c4c04b22c71c52bbb96ed9d2205b036f83950a9ef2ada67c20bd64b427d238c0651c4668",
          "sha256": "40352b3fc0834d5830f66d40100fc8afa8ac73e24a134c7779bd42b72f2d6506",
          "sha1": "4d1f5fcf982ec75223a3ee44169e268b6dd044f7",
          "md5": "e7f22a3cc55d98c2c8030f069c8963a5"
        }
      ]
    }
  ]
}
