{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.logging.log4j",
    "module": "log4j-to-slf4j",
    "version": "2.25.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "biz.aQute.bnd",
          "module": "biz.aQute.bnd.annotation",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.38.0"
          }
        },
        {
          "group": "org.osgi",
          "module": "org.osgi.annotation.bundle",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.osgi",
          "module": "org.osgi.annotation.versioning",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "log4j-to-slf4j-2.25.4.jar",
          "url": "log4j-to-slf4j-2.25.4.jar",
          "size": 24172,
          "sha512": "c1e610d232c07813e36b26cf0b1375ec9ac0761f81c7cf9f03f6fae2d543a6f8201b2f56372d5647af5c8b359b46a2d9e7974fff8ab6fda9f1c981e4a961ff29",
          "sha256": "d7b78fc0aaaa5e8ada388b29d718b0ab187e512965bed0b259bb4ab299f13db2",
          "sha1": "68df56640a5d245192e91bd2ac89e504b477cc10",
          "md5": "b3d45f5534aa71da607e403ce1519977"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.4"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "log4j-to-slf4j-2.25.4.jar",
          "url": "log4j-to-slf4j-2.25.4.jar",
          "size": 24172,
          "sha512": "c1e610d232c07813e36b26cf0b1375ec9ac0761f81c7cf9f03f6fae2d543a6f8201b2f56372d5647af5c8b359b46a2d9e7974fff8ab6fda9f1c981e4a961ff29",
          "sha256": "d7b78fc0aaaa5e8ada388b29d718b0ab187e512965bed0b259bb4ab299f13db2",
          "sha1": "68df56640a5d245192e91bd2ac89e504b477cc10",
          "md5": "b3d45f5534aa71da607e403ce1519977"
        }
      ]
    }
  ]
}
