{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.22"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.1.0.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.1.0.jar",
          "size": 4742,
          "sha512": "a127203725d4d705dfbc4ca3360290bb041ccc443838e851b4642c4434638b83e7f2dadb91e53a8b7de7548dd3688a02879033ce886c478aff50cc376b7b620b",
          "sha256": "135fa0b7a4232c64b975f348cab39e2259d36a18e14768f5f213147a4febf68d",
          "sha1": "6107a851e178c1233b64634270b11b8d5490733a",
          "md5": "5993ff1e3da9deb87c293d5929ae15c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.22"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.22"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.1.0.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.1.0.jar",
          "size": 4742,
          "sha512": "a127203725d4d705dfbc4ca3360290bb041ccc443838e851b4642c4434638b83e7f2dadb91e53a8b7de7548dd3688a02879033ce886c478aff50cc376b7b620b",
          "sha256": "135fa0b7a4232c64b975f348cab39e2259d36a18e14768f5f213147a4febf68d",
          "sha1": "6107a851e178c1233b64634270b11b8d5490733a",
          "md5": "5993ff1e3da9deb87c293d5929ae15c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.1.0-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.1.0-javadoc.jar",
          "size": 4742,
          "sha512": "a127203725d4d705dfbc4ca3360290bb041ccc443838e851b4642c4434638b83e7f2dadb91e53a8b7de7548dd3688a02879033ce886c478aff50cc376b7b620b",
          "sha256": "135fa0b7a4232c64b975f348cab39e2259d36a18e14768f5f213147a4febf68d",
          "sha1": "6107a851e178c1233b64634270b11b8d5490733a",
          "md5": "5993ff1e3da9deb87c293d5929ae15c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.1.0-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.1.0-sources.jar",
          "size": 4742,
          "sha512": "a127203725d4d705dfbc4ca3360290bb041ccc443838e851b4642c4434638b83e7f2dadb91e53a8b7de7548dd3688a02879033ce886c478aff50cc376b7b620b",
          "sha256": "135fa0b7a4232c64b975f348cab39e2259d36a18e14768f5f213147a4febf68d",
          "sha1": "6107a851e178c1233b64634270b11b8d5490733a",
          "md5": "5993ff1e3da9deb87c293d5929ae15c0"
        }
      ]
    }
  ]
}
